remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- search



theme:
  custom_dir: 'assets'
  favicon: /favicon.png
  features:
    - navigation.tabs
    - navigation.instant

title: witherslayer67's Home Page
description: Bookmark this to keep an eye on my project updates!
