remote_theme: cotes2020/jekyll-theme-chirpy@v6.3.1
plugins:
- jekyll-remote-theme
- search



theme:
  custom_dir: 'assets'
  favicon: /favicon.png

title: witherslayer67's Home Page
description: Bookmark this to keep an eye on my project updates!
