remote_theme: sproogen/modern-resume-theme@v2.0.10
plugins:
- jekyll-remote-theme
- search



theme:
  custom_dir: 'assets'
  favicon: /favicon.png

title: witherslayer67's Home Page
description: Bookmark this to keep an eye on my project updates!
